-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.libros
(
    id_libro uuid NOT NULL DEFAULT gen_random_uuid(),
    titulo character varying COLLATE pg_catalog."default" NOT NULL,
    autor character varying COLLATE pg_catalog."default" NOT NULL,
    genero character varying COLLATE pg_catalog."default" NOT NULL,
    num_paginas integer NOT NULL,
    sinopsis text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT libro_pkey PRIMARY KEY (id_libro)
);

CREATE TABLE IF NOT EXISTS public.prestamos
(
    id_prestamo uuid NOT NULL DEFAULT gen_random_uuid(),
    id_libro uuid NOT NULL,
    dni_usuario integer NOT NULL,
    CONSTRAINT prestamos_pkey PRIMARY KEY (id_prestamo)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying COLLATE pg_catalog."default" NOT NULL,
    dni_usuario integer NOT NULL,
    CONSTRAINT usuarios_pk PRIMARY KEY (dni_usuario)
);

ALTER TABLE IF EXISTS public.prestamos
    ADD CONSTRAINT libro FOREIGN KEY (id_libro)
    REFERENCES public.libros (id_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_libro
    ON public.prestamos(id_libro);


ALTER TABLE IF EXISTS public.prestamos
    ADD CONSTRAINT usuario FOREIGN KEY (dni_usuario)
    REFERENCES public.usuarios (dni_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_usuario
    ON public.prestamos(dni_usuario);

END;